name: checkguard

# Run this workflow every time a new commit pushed to your repository

on: [push, pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  checkguard:
    # Name the Job
    name: Check include guard naming convention
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        uses: actions/setup-python@v2
        with:
            python-version: '3.7'
      - run: |
          pip install guardonce
          checkguard --version
      # - id: files
      #   uses: jitterbit/get-changed-files@v1
      # - run: checkguard --version
